---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: cloud.exchange.fct.inventory-backorder.0
  namespace: fbg
  labels:
    strimzi.io/cluster: fbg-sportsbook-msk
spec:
  partitions: 3
  replicas: 3
  config:
    max.message.bytes: 1048576 # 1 MB
    cleanup.policy: compact
    min.compaction.lag.ms: 21600000 # 6 hours - min time before record is compacted
    max.compaction.lag.ms: 86400000 # 1 day - max time after which record is compacted
    delete.retention.ms: 86400000 # 1 day - how long tombstone records are kept
    min.cleanable.dirty.ratio: 0.25
    segment.bytes: 104857600  # 100 MB
    retention.ms: -1 # rely only on compaction for cleanup
    min.insync.replicas: 2
    unclean.leader.election.enable: false # only caught up replicas can be leader
